# Use official Python base image
FROM python:3.11.12

# Set working directory
WORKDIR /app

# Ensure INFO logs (e.g. matplotlib.font_manager) are silenced globally
ENV PYTHONLOGLEVEL=WARNING

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

# Create IPython startup to suppress any remaining font_manager logs in notebooks
RUN mkdir -p /root/.ipython/profile_default/startup && \
    echo "import logging; logging.getLogger('matplotlib.font_manager').setLevel(logging.ERROR)" \
    > /root/.ipython/profile_default/startup/00-suppress-font-logs.py

# Copy requirements and install Python deps
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Install JupyterLab and ipywidgets
RUN pip install --no-cache-dir jupyterlab==4.4.1 ipywidgets

# Copy SSL certificates (generated by mkcert)
COPY localhost.pem /etc/ssl/certs/localhost.pem
COPY localhost-key.pem /etc/ssl/private/localhost-key.pem

# Expose JupyterLab port
EXPOSE 8888

# Launch JupyterLab over HTTPS, restrict origin
CMD ["jupyter", "lab", \
     "--ip=0.0.0.0", \
     "--port=8888", \
     "--allow-root", \
     "--NotebookApp.token=''", \
     "--NotebookApp.allow_origin=https://garmentiq.ly.gd.edu.kg", \
     "--certfile=/etc/ssl/certs/localhost.pem", \
     "--keyfile=/etc/ssl/private/localhost-key.pem"]
