# -*- coding: utf-8 -*-
"""plot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eXZ-3LA4Vf5iYypAke5qDPqXGEKn2myn
"""

import cv2
import matplotlib.pyplot as plt

def display_image_with_projections(img_path, intersection_point1, intersection_point2):
    """
    Displays an image with two projection points marked.

    Args:
        img_path (str): Path to the image.
        intersection_point1 (tuple): (x, y) coordinates for the first projection point.
        intersection_point2 (tuple): (x, y) coordinates for the second projection point.
    """
    img = cv2.cvtColor(cv2.imread(img_path), cv2.COLOR_BGR2RGB)
    plt.figure(figsize=(24, 16))
    plt.imshow(img)
    plt.axis('on')
    plt.scatter(*intersection_point1, c='blue', s=5, label='Projection')
    plt.scatter(*intersection_point2, c='blue', s=5, label='Projection')
    plt.legend()
    plt.show()